version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode_phu
    restart: always
    ports:
      - 9870:9870
      - 9000:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - ./hadoop_data:/hadoop_data
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network_phu
    profiles:
      - docker_hadoop_phu

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode_phu
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network_phu
    depends_on:
      - namenode
    profiles:
      - docker_hadoop_phu
  
  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager_phu
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network_phu
    depends_on:
      - namenode
      - datanode
    profiles:
      - docker_hadoop_phu

  nodemanager1:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager_phu
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network_phu
    depends_on:
      - resourcemanager
    profiles:
      - docker_hadoop_phu
  
  historyserver:
    image: bde2020/hadoop-historyserver:2.0.0-hadoop3.2.1-java8
    container_name: historyserver_phu
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9000 namenode:9870 datanode:9864 resourcemanager:8088"
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network_phu
    depends_on:
      - resourcemanager
    profiles:
      - docker_hadoop_phu

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master_phu
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SPARK_MASTER_OPTS="-Dspark.deploy.defaultCores=1"
    volumes:
      - spark_data:/spark-data
    networks:
      - hadoop_network_phu
    depends_on:
      - namenode
      - datanode
    profiles:
      - docker_hadoop_phu

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1_phu
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      # - SPARK_WORKER_CORES=1
      # - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_WEBUI_PORT=8081
    ports:
      - "8081:8081"
    volumes:
      - spark_data:/spark-data
    networks:
      - hadoop_network_phu
    depends_on:
      - spark-master
    profiles:
      - docker_hadoop_phu

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2_phu
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      # - SPARK_WORKER_CORES=1
      # - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_WEBUI_PORT=8082
    ports:
      - "8082:8082"
    volumes:
      - spark_data:/spark-data
    networks:
      - hadoop_network_phu
    depends_on:
      - spark-master
    profiles:
      - docker_hadoop_phu

  jupyterhub:
    build: 
      context: .
      dockerfile: Dockerfile.jupyterhub
    container_name: jupyterhub_phu
    ports:
      - "8000:8000"
    environment:
      - JUPYTER_ENABLE_LAB=1
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk
      # - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-8-openjdk/bin
      - PYSPARK_PYTHON=/usr/bin/python3
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3
      - SPARK_MASTER=spark://spark-master:7077
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      # - ./userlist:/srv/jupyterhub/userlist
      - ./jupyterhub_data/:/srv/share_data
      - ./jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - ./DAC/:/home/phundh
    networks:
      - hadoop_network_phu
    depends_on:
      - spark-master
    profiles:
      - docker_hadoop_phu

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  spark_data:
  jupyterhub_data:
    driver: local

networks:
  hadoop_network_phu:
    driver: bridge
